In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print('Vectorized version:' + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("Non - Vectorized version:" + str(1000*(toc-tic)) + "ms")


249842.08859598025
Vectorized version:2.0020008087158203ms
249842.08859598043
Non - Vectorized version:545.7243919372559ms


In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
a

array([ 2.69720199,  0.70173402,  0.17240938, -1.20856852,  0.53918627])

In [3]:
print(a.shape)

(5,)


In [8]:
import requests
from bs4 import BeautifulSoup

# Send a GET request to the Google Trends homepage
response = requests.get("https://trends.google.com/")

# Parse the response using BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

# Find the elements containing the names of the top trending topics
topic_elements = soup.find_all("div", class_="list-item-container")

# Extract the text from each element and print it
for element in topic_elements:
    print(element.text)

In [11]:
soup.find_all(class_="list-item-container")

[]

In [1]:
import numpy as np
a = np.array([[ 0.0,  0.0,  0.0],
                [10.0, 10.0, 10.0],
                [20.0, 20.0, 20.0],
                [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])

a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [3]:
print(a.shape)
print(b.shape)

(4, 3)
(3,)


In [4]:
c = np.array([[1.0, 2.0, 3.0, 4.0]])

In [8]:
c.reshape(4, 1)+a

array([[ 1.,  1.,  1.],
       [12., 12., 12.],
       [23., 23., 23.],
       [34., 34., 34.]])

In [6]:
a+c

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 